export const cartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEMS: 'ADD_ITEMS',
    REMOVE_ITEMS: 'REMOVE_ITEMS',
    REDUCE_ITEMS: 'REDUCE_ITEMS',
    CLEAR_CART: 'CLEAR_CART'
}